config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "boards#index"

  resources :boards do
    resources :topics do
      resources :replies
    end
  end

  resources :topics do
    collection do
      post :pin
    end
    resources :replies
  end

  resources :articles do
    resources :comments
  end

  resources :replies do
    collection do
      post :report
      post :unreport
    end
  end

  resources :users

  get "login", to: "sessions#login"
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy"
  get "logout" => "sessions#destroy"

  get "admin" => "admin#index"
  get "admin/reported" => "admin#showReported"
  get "admin/boards" => "boards#adminIndex"
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :board
  has_many :reply, dependent: :destroy

  validates :name, :subject, :comment, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  invisible_captcha only: [ :create ], honeypot: :maintitle

  def new
    @topic = Topic.new
  end

  def create
    @boards = Board.all()
    @board = Board.find(params[:board_id])
    @topic = @board.topics.create(topic_params)
    @topic.assign_attributes(topic_params)

    if @topic.persisted?
      redirect_to board_path(@board.short_name)
    else
      render "boards/show", status: :unprocessable_entity, locals: {
        boards: @boards,
        board: @board,
        topic: @topic
      }
    end
  end

  def show
    @boards = Board.all()
    @board = Board.find(params[:board_id])
    @topic = Topic.find(params[:id])
  end

  def pin
    @topic = Topic.find(params[:id]).toggle!(:pin)
    redirect_back fallback_location: root_path, status: :see_other
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy!

    redirect_back fallback_location: root_path, status: :see_other
  end

  private
    def topic_params
      params.require(:topic).permit(:name, :subject, :comment).merge(pin: :false)
    end
end

app/views/topics/_form.html.erb
<div class="topic_form">
  <div class="topic_container">
    <h2 class="topic_title">Topic</h2>
    <%= form_with model: [ board, board.topics.build ] do |form| %>
      <%= form.invisible_captcha :maintitle %>
      <p>
        <%= form.label :name %> <span class="form_required">*</span><br>
        <%= 
          form.text_field :name,
          class: "form_textfield",
          :value => if defined? topic.name then topic.name else "Anon" end 
        %>
        <% if defined? topic.errors %>
          <% topic.errors.full_messages_for(:name).each do |message| %>
            <div class="form_error"><%= message %></div>
          <% end %>
        <% end %>
      </p>
      <p>
        <%= form.label :subject %> <span class="form_required">*</span><br>
        <%= 
          form.text_field :subject,
          class: "form_textfield",
          :value => if defined? topic.subject then topic.subject else "" end 
        %>
        <% if defined? topic.errors %>
          <% topic.errors.full_messages_for(:subject).each do |message| %>
            <div class="form_error"><%= message %></div>
          <% end %>
        <% end %>
      </p>
      <p>
        <%= form.label :comment %> <span class="form_required">*</span> 
        <%= 
          form.text_area :comment,
          class: "form_textarea",
          spellcheck: "false",
          size:"70x5",
          :value => if defined? topic.comment then topic.comment else "" end 
        %>
        <% if defined? topic.errors %>
          <% topic.errors.full_messages_for(:comment).each do |message| %>
            <div class="form_error"><%= message %></div>
          <% end %>
        <% end %>
      </p>
      <p>
        <%= form.submit class: "form_button" %>
      </p>
    <% end %>
  </div>
</div>

app/views/topics/_topic.html.erb
<% topics.each do |topic| %>
  <% if topic.id != nil %>
    <% if logged_in? %>
        <div class="catalog_topic">
           <a class="catalog_link" href="/boards/<%= board.id %>/topics/<%= topic.id %>">
             <strong><%= topic.subject %> - <%= topic.created_at.strftime("%F %T") %></strong>
              <% if topic.pin %>
                <p>Pinned</p>
              <% end %>
             <p>Replies: <%= topic.reply_ids.count %></p>
             <p>
               <%= topic.comment %>
             </p>
           </a>
           <%= 
             button_to "Pin", 
             {:controller => :topics, :action => 'pin', :id => topic.id },
             :form_class => "admin_button_form",
             :class => "submenu_button",
             :method => :pin 
           %>
           <%= 
             button_to "Delete", 
             {:controller => :topics, :action => 'destroy', :id => topic.id },
             :method => :delete, 
             :form_class => "admin_button_form",
             :class => "submenu_button",
             data: { turbo_confirm: "Are you sure?" }
           %>
        </div>
     <% else %>
      <a class="catalog_link" href="/boards/<%= board.id %>/topics/<%= topic.id %>">
        <div class="catalog_topic">
          <strong><%= topic.subject %> - <%= topic.created_at.strftime("%F %T") %></strong>
            <% if topic.pin %>
              <p>Pinned</p>
            <% end %>
            <p>Replies: <%= topic.reply_ids.count %></p>
            <p>
              <%= topic.comment %>
            </p>
        </div>
      </a>
    <% end %>
  <% end %>
<% end %>

app/views/topics/show.html.erb
<%= render "shared/boardslist", boards: @boards %>

<h1 class="board_show_title">/<%= @board.short_name %>/ - <%= @board.name %></h1>

<div class="board_options">
  <div class="board_options_left">
    [<a href="/boards/<%= @board.short_name %>">Back</a>]
    [<a href="#bottom">Bottom</a>] 
    [<a href="">Update</a>] 
  </div>

  <div class="board_options_right">
    <span title="Amount of replies"><%= @topic.reply.count %></span>
  </div>
</div>

<div class="replies_op">
  <h2 class="replies_op_title"><%= @topic.subject %> - <span class="anon_name"><%= @topic.name %></span> - <%= @topic.created_at.strftime("%F %T") %> - <%= @topic.id %> </h2>
  <p><%= simple_format(@topic.comment) %></p>
</div>

<div class="reply_catalog">
  <%= render @topic.reply %>
</div>

<%= render "replies/form", topic: @topic, reply: @reply %>