config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "boards#index"

  resources :boards do
    resources :topics do
      resources :replies
    end
  end

  resources :topics do
    collection do
      post :pin
    end
    resources :replies
  end

  resources :articles do
    resources :comments
  end

  resources :replies do
    collection do
      post :report
      post :unreport
    end
  end

  resources :users

  get "login", to: "sessions#login"
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy"
  get "logout" => "sessions#destroy"

  get "admin" => "admin#index"
  get "admin/reported" => "admin#showReported"
  get "admin/boards" => "boards#adminIndex"
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :topics
  accepts_nested_attributes_for :topics
  validates :name, :short_name, uniqueness: true, presence: true
  validates :name, length: { minimum: 5 }
  validates :short_name, length: { minimum: 1 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  include UsersHelper
  before_action :require_login, only: [:adminIndex, :new, :create, :edit, :update]

  def index
    @boards = Board.all
  end

  def adminIndex
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)

    if @board.save
        redirect_to({ action: "adminIndex" })
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    short_name = params.extract_value(:id)
    @board = Board.find_by_short_name(short_name)
    @boards = Board.all

    @sort = params[:sort] ? params[:sort] : "created_at"

    if params[:sort] == "name"
      @default = ""
    elsif params[:sort] == "created_at"
      @default = Time.now
    elsif params[:sort] == nil
      @default = Time.now
    else
      @default = ""
    end

    if params[:sort] == "name"
      @topics = @board.topics.select { |e| e["pin"] == true } +
        @board.topics.select { |e| e["pin"] == false }.sort_by { |e| e[@sort] || @default }
    else
      @topics = @board.topics.select { |e| e["pin"] == true } +
        @board.topics.select { |e| e["pin"] == false}.sort_by { |e| e[@sort] || @default }.reverse
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])

    if @board.update(board_params)
      redirect_to({ action: "adminIndex" })
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy!

    redirect_back fallback_location: root_path, status: :see_other
  end

  private
    def board_params
      params.require(:board).permit(:name, :short_name)
    end
    def require_login
      unless current_user
        redirect_to login_url
      end
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<h2 class="users_title">Boards</h2>
<div class="form_body">
  <%= form_with model: board do |form| %>
    <%= form.label :name %>
    <%= 
        form.text_field :name,
        class: "form_textfield"
    %>
    <% if defined? board.errors %>
      <% board.errors.full_messages_for(:name).each do |message| %>
        <div class="form_error"><%= message %></div>
      <% end %>
    <% end %>
    <%= form.label :short_name %>
    <%= 
      form.text_field :short_name, 
      class: "form_textfield"
    %>
    <% if defined? board.errors %>
      <% board.errors.full_messages_for(:short_name).each do |message| %>
        <div class="form_error"><%= message %></div>
      <% end %>
    <% end %>
    <%= form.submit "Create Board", class: "form_button"%>
  <% end %> 
</div>

app/views/boards/adminIndex.html.erb
<%= render "shared/adminmenu" %>

<div class="users_menu">
  <%= link_to "Create board", "/boards/new", class: "admin_link" %>
</div>

<div class="users_container">
  <h2 class="users_title">Boards</h2>
  <div class="users_list">
    <% @boards.each do |board| %>
      <p>
        <b>Name</b>: <%= board.name %> </br>
        <b>Shortname</b>: <%= board.short_name %> </br>
          <%= 
            button_to "Edit", 
            edit_board_path(board),
            :form_class => "admin_button_form",
            :class => "users_button",
            :method => :get 
           %>
          <%= 
            button_to "Delete", 
            {:controller => :boards, :action => 'destroy', :id => board.id },
            :method => :delete, 
            :form_class => "admin_button_form",
            :class => "users_button",
            data: { turbo_confirm: "Are you sure?" }
           %>
      </p>
    <% end %>
  </div>
</div>

app/views/boards/edit.html.erb
<%= render "shared/adminmenu" %>

<h1 class="title">Edit Board Page</h1>
<div class="users_menu">
  <%= link_to "Boards overview", "/admin/boards", :class => "admin_button" %>
</div>
<div class="container">
  <%= render "form", board: @board %>
</div>

app/views/boards/index.html.erb
<%= render "shared/adminmenu" %>

<h1 class="openchan_title">Openchan</h1>

<div class="boards_container">
  <h2 class="boards_title">Boards</h2>
  <div class="boards_list">
    <% @boards.each do |board| %>
      <a href="/boards/<%= board.short_name %>">
        <p><%= board.name %></p>
      </a>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<%= render "shared/adminmenu" %>

<h1 class="title">New Boards Page</h1>
<div class="users_menu">
  <%= link_to "User overview", "/users", :class => "admin_button" %>
</div>
<div class="container">
  <%= render "form", board: @board %>
</div>

app/views/boards/show.html.erb
<%= render "shared/boardslist", boards: @boards %>

<h1 class="board_show_title">/<%= @board.short_name %>/ - <%= @board.name %></h1>

<div class="board_options">
  <div class="board_options_left">
    [<a href="">Refresh</a>] 
  </div>


  <div class="board_options_right">
    <%= form_with(url: board_path(@board.short_name), method: :get, local: true) do |form| %>
      Sort By: <%= select_tag(:sort, options_for_select([
        ['New', 'created_at'],
        ['Name', 'name']
      ], @sort)) %>
      <%= form.submit "Sort", class: "submenu_button" %>
    <% end %>
  </div>
</div>

<%= render "topics/form", board: @board, topic: @topic %>

<div class="board_catalog">
  <%= render "topics/topic", 
    board: @board,
    topics: @topics 
  %>
</div>